/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import javax.swing.*;
import interno_telas.*;

/**
 *
 * @author albert
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        MCadCurso = new javax.swing.JMenuItem();
        MCadDisc = new javax.swing.JMenuItem();
        MCadAluno = new javax.swing.JMenuItem();
        MCadProf = new javax.swing.JMenuItem();
        MMCurso = new javax.swing.JMenu();
        MMCursos = new javax.swing.JMenuItem();
        MMDisc = new javax.swing.JMenuItem();
        MMAluno = new javax.swing.JMenuItem();
        MMProf = new javax.swing.JMenuItem();
        MMCP = new javax.swing.JMenuItem();
        MMCD = new javax.swing.JMenuItem();
        MMPD = new javax.swing.JMenuItem();
        MMAD = new javax.swing.JMenuItem();
        JMSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU");

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1005, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        jMenu2.setText("Cadastrar");

        MCadCurso.setText("Curso");
        MCadCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MCadCursoActionPerformed(evt);
            }
        });
        jMenu2.add(MCadCurso);

        MCadDisc.setText("Disciplina");
        MCadDisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MCadDiscActionPerformed(evt);
            }
        });
        jMenu2.add(MCadDisc);

        MCadAluno.setText("Aluno");
        MCadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MCadAlunoActionPerformed(evt);
            }
        });
        jMenu2.add(MCadAluno);

        MCadProf.setText("Professor");
        MCadProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MCadProfActionPerformed(evt);
            }
        });
        jMenu2.add(MCadProf);

        jMenuBar1.add(jMenu2);

        MMCurso.setText("Mostrar");

        MMCursos.setText("Cursos");
        MMCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMCursosActionPerformed(evt);
            }
        });
        MMCurso.add(MMCursos);

        MMDisc.setText("Disciplina");
        MMDisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMDiscActionPerformed(evt);
            }
        });
        MMCurso.add(MMDisc);

        MMAluno.setText("Aluno");
        MMAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMAlunoActionPerformed(evt);
            }
        });
        MMCurso.add(MMAluno);

        MMProf.setText("Professor");
        MMProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMProfActionPerformed(evt);
            }
        });
        MMCurso.add(MMProf);

        MMCP.setText("Cursos/Professores");
        MMCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMCPActionPerformed(evt);
            }
        });
        MMCurso.add(MMCP);

        MMCD.setText("Cursos/Disciplinas");
        MMCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMCDActionPerformed(evt);
            }
        });
        MMCurso.add(MMCD);

        MMPD.setText("Professores/Disciplinas");
        MMPD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMPDActionPerformed(evt);
            }
        });
        MMCurso.add(MMPD);

        MMAD.setText("Aluno/Disciplina ");
        MMAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMADActionPerformed(evt);
            }
        });
        MMCurso.add(MMAD);

        jMenuBar1.add(MMCurso);

        JMSair.setText("Sair");
        JMSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMSairMouseClicked(evt);
            }
        });
        JMSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMSairActionPerformed(evt);
            }
        });
        jMenuBar1.add(JMSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MMProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMProfActionPerformed
    Professor prof=new Professor();
    prof.setVisible(true);
    Desktop.add(prof);// TODO add your handling code here:
    }//GEN-LAST:event_MMProfActionPerformed

    private void JMSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMSairActionPerformed
        
    }//GEN-LAST:event_JMSairActionPerformed

    private void JMSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMSairMouseClicked
int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Atenção",               JOptionPane.YES_NO_OPTION);
    if(sair==JOptionPane.YES_OPTION){
            System.exit(0);
        }    }//GEN-LAST:event_JMSairMouseClicked

    private void MCadCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCadCursoActionPerformed
        Curso curso = new Curso();
        curso.setVisible(true);
    }//GEN-LAST:event_MCadCursoActionPerformed

    private void MCadDiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCadDiscActionPerformed
        Disciplinas discs = new Disciplinas();
        discs.setVisible(true);
    }//GEN-LAST:event_MCadDiscActionPerformed

    private void MMAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMAlunoActionPerformed
        Aluno aluno = new Aluno();
        aluno.setVisible(true);
        Desktop.add(aluno);
    }//GEN-LAST:event_MMAlunoActionPerformed

    private void MMDiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMDiscActionPerformed
        Disciplina disc = new Disciplina();
        disc.setVisible(true);
        Desktop.add(disc);
    }//GEN-LAST:event_MMDiscActionPerformed

    private void MMCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMCursosActionPerformed
        Cursos cursos = new Cursos();
        cursos.setVisible(true);
        Desktop.add(cursos);
    }//GEN-LAST:event_MMCursosActionPerformed

    private void MCadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCadAlunoActionPerformed
        Alunos alunos = new Alunos();
        alunos.setVisible(true);
        
    }//GEN-LAST:event_MCadAlunoActionPerformed

    private void MCadProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCadProfActionPerformed
        Professores profs = new Professores();
        profs.setVisible(true);
        
    }//GEN-LAST:event_MCadProfActionPerformed

    private void MMCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMCPActionPerformed
        CProf cprof = new CProf();
        cprof.setVisible(true);
        Desktop.add(cprof);
              
    }//GEN-LAST:event_MMCPActionPerformed

    private void MMCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMCDActionPerformed
      CDisc cdisc = new CDisc();
      cdisc.setVisible(true);
      Desktop.add(cdisc);
    }//GEN-LAST:event_MMCDActionPerformed

    private void MMPDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMPDActionPerformed
        PDisc pdisc = new PDisc();
        pdisc.setVisible(true);
        Desktop.add(pdisc);
    }//GEN-LAST:event_MMPDActionPerformed

    private void MMADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMADActionPerformed
        ADisc adisc = new ADisc();
        adisc.setVisible(true);
        Desktop.add(adisc);
    }//GEN-LAST:event_MMADActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenu JMSair;
    private javax.swing.JMenuItem MCadAluno;
    private javax.swing.JMenuItem MCadCurso;
    private javax.swing.JMenuItem MCadDisc;
    private javax.swing.JMenuItem MCadProf;
    private javax.swing.JMenuItem MMAD;
    private javax.swing.JMenuItem MMAluno;
    private javax.swing.JMenuItem MMCD;
    private javax.swing.JMenuItem MMCP;
    private javax.swing.JMenu MMCurso;
    private javax.swing.JMenuItem MMCursos;
    private javax.swing.JMenuItem MMDisc;
    private javax.swing.JMenuItem MMPD;
    private javax.swing.JMenuItem MMProf;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
